### ISSUE TITLE
Initializing the Driver from Environmental Variables makes out tests run for hours, and times out the build.

### ISSUE THREAD

**Issue by jfreal** [Microsoft/azure-pipelines-image-generation#373]
I've been asked to move my issue over here:
https://github.com/MicrosoftDocs/vsts-docs/issues/2379

If we run our tests locally and on Azure Devops with Driver = new ChromeDriver(); the tests run fine.

If we use Driver = new ChromeDriver(Environment.GetEnvironmentVariable("ChromeWebDriver")); the tests take forever and will eventually exceed a six hour time limit.

![image](https://user-images.githubusercontent.com/144533/48679394-bd95d800-eb5d-11e8-8fe1-8b7157df0b87.png)

Running with a remote Selenium with Browser Stack's Automate product works fine as well.

**Comment by DavidStaheli** [comment]
Hi @jfreal.  Can you tell us which Microsoft-hosted agent you see this problem on (Ubuntu, macOS, Windows)?  Thank you.

**Comment by jfreal** [comment]
@DavidStaheli Windows, thanks.

**Comment by prawalagarwal** [comment]
@jfreal Apologies for late reply here. If you are still facing this issue, please go through [this post](https://stackoverflow.com/questions/15067107/difference-between-webdriver-dispose-close-and-quit) for a safe cleanup of tests using selenium framework. We suggest you to use browser.quit() and driver.quit() in your tests cleanup. The tests run forever because they wait on the test process to exit safely, which in turn waits for the drivers to exit.

**Comment by jfreal** [comment]
My test cleanup looks like the code in the documentation I followed here: 
https://docs.microsoft.com/en-us/azure/devops/pipelines/test/continuous-test-selenium?view=vsts

` [TestCleanup]
        public void TestCleanup()
        {
            Driver.Quit();
        }`

The tests run fine on Azure Devops except when I use the Driver = new ChromeDriver(Environment.GetEnvironmentVariable("ChromeWebDriver")); setting.

**Comment by kaadhina** [comment]
@jfreal can you please let us know the version of chrome driver that you are packaging with your test binaries? (The version that works).

**Comment by jfreal** [comment]
@kaadhina I don't package any binaries.  I use whatever driver is installed on my system or by the WebDriver nuget package.

In debug mode I can see in the capabilities dictionary of driver the version is  70.0.3538.110

![image](https://user-images.githubusercontent.com/144533/49802674-86a98100-fd1b-11e8-94e5-974de74cb0b5.png)

**Comment by jfreal** [comment]
@kaadhina 

2.44.609538

Driver.Quit is hit.

![image](https://user-images.githubusercontent.com/144533/49948935-71bb2200-fec2-11e8-934a-5c5098500559.png)

Just to clarify again.  The tests run fine in BrowserStack and in my local environment.

I'll kick off a build with the environmental variable being used and let you know about the results.

**Comment by jfreal** [comment]
Here are some of the errors we are seeing:

2018-12-12T03:13:20.7201509Z  Initialization method CS.Portal.E2e.Tests.DisabledActions.CampaignListSpendingDisabledTests.SetupTest threw exception. OpenQA.Selenium.WebDriverException: The HTTP request to the remote WebDriver server for URL http://localhost:2040/session timed out after 60 seconds. ---> System.Net.WebException: The operation has timed out.
2018-12-12T03:13:20.7203324Z TestCleanup method CS.Portal.E2e.Tests.DisabledActions.CampaignListSpendingDisabledTests.TestCleanup threw exception. System.NullReferenceException: System.NullReferenceException: Object reference not set to an instance of an object..

**Comment by ShreyasRmsft** [comment]
@jfreal this latest issue is totally unrelated to the initial one.

> 2018-12-12T03:13:20.7201509Z Initialization method CS.Portal.E2e.Tests.DisabledActions.CampaignListSpendingDisabledTests.SetupTest threw exception. OpenQA.Selenium.WebDriverException: The HTTP request to the remote WebDriver server for URL http://localhost:2040/session timed out after 60 seconds. ---> System.Net.WebException: The operation has timed out.

The above is clearly a test failure where a connection timeout occurred.


> 2018-12-12T03:13:20.7203324Z TestCleanup method CS.Portal.E2e.Tests.DisabledActions.CampaignListSpendingDisabledTests.TestCleanup threw exception. System.NullReferenceException: System.NullReferenceException: Object reference not set to an instance of an object..

And this is happening because the driver never got initialized. I'd suggest where ever you are trying to quit/dispose the driver use it in the following way

`driver?.Dispose();`

**Comment by jfreal** [comment]
We call Driver.Dispose() as indicated earlier in the comments.

The tests run fine locally and with a remote selenium.

The point of the last comment is now the tests take six hours and fail
regardless of whether I initialize the driver with the environmental
variable.

I'm assuming Driver is null because there is an exception initializing the
driver.

**Comment by ShreyasRmsft** [comment]
@jfreal so here's the situation:

I believe the build only hangs when the test (your test actually fails due to a product issue) fails.

The reason this happens is that selenium does not dispose of all its resources some times when the test fails. This is something I have observed.

Now the gap from our end is that the build agent waits on all child process to die out before ending the current task and moving on to the next one. This is the reason you don't see a hang locally. Even though there might be stale resources/processes left lying about after a test run they get forcefully terminated.

Now we could replicate a similar behavior on the pipeline but one would argue that we are now tampering with the user test code behavior. What if there genuinely was process lingering about doing cleanup etc etc.

This is something we will have to think through.

However there exists a more elegant solution that the test frameworks (like MsTest) and the testplatform provide to ensure this doesn't happen.  There's a series of timeouts in both the test framework (testtimeout, session timeout) and the testplatform (test run timeout). You can set these values to ensure the tests timeout if the take longer than a certain duration.

Please follow the guidelines in https://github.com/Microsoft/azure-pipelines-tasks/issues/8733.

Here are a few links for setting timeouts

https://github.com/Microsoft/vstest-docs/blob/master/RFCs/0011-Test-Session-Timeout.md

https://github.com/Microsoft/testfx/issues/26

Lemme know if following any/all of these solves your problem.

**Comment by jfreal** [comment]
Thanks, I'll run these changes this week and see what happens.

**Comment by ShreyasRmsft** [comment]
@jfreal any updates?

**Comment by jfreal** [comment]
Hey sorry for the late reply.  Setting a test session timeout has fixed the 6 hour run time.  We still have tests fail only on azure devops but at least the tests runs work.  Thanks for the help.

**Comment by ShreyasRmsft** [comment]
@jfreal we have additionally made a few changes in the task that should end the task regardless of undisposed derivers etc., if the tests have completed execution. This should get rolled out soon. Will update this thread once the changes have been deployed.

> We still have tests fail only on azure devops but at least the tests runs work.
@jfreal we can maybe help out with this if you can create a sample repro public project for us.

**Comment by jfreal** [comment]
@ShreyasRmsft I may not be able to create a public project.  This is an internal app and we may not be able to give the world access.  Hmm, I'll see what I can do, but I wouldn't expect much progress here.

FYI a local computer run of the tests resulted in one failure.  The same tests run last night on Azure DevOps resulted in eight failures.

All the failures are WebDriverTimeoutException's.

My theory is the resources of the Azure chrome drivers aren't high enough to deal with the website and something must be crashing/freezing in the client code.  I'm going to run a comparison test on BrowserStack at some point this week.  I'll keep you in the loop with what I find.

**Comment by jfreal** [comment]
@ShreyasRmsft I just had a test run for 6 hours even with the timeout settings in place.

Here is the stack trace from the exception which I assume failed to close the process.

This was from a manually queued pipeline build so maybe the runsettings weren't applied?

TestCleanup()

```

        [TestCleanup]
        public void TestCleanup()
        {
            Driver.Close();
            Driver.Quit();
            Driver.Dispose();
        }
```

2019-01-22T16:01:20.7041054Z TestCleanup method CS.Portal.E2e.Tests.Admin.DiversityFiltersAdmin.DiversityFiltersAdminTests.TestCleanup threw exception. System.NullReferenceException: System.NullReferenceException: Object reference not set to an instance of an object..
2019-01-22T16:01:20.7042037Z Stack Trace:
2019-01-22T16:01:20.7042096Z     at System.Net.HttpWebRequest.GetResponse()
2019-01-22T16:01:20.7042201Z    at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
2019-01-22T16:01:20.7042259Z --- End of inner exception stack trace ---
2019-01-22T16:01:20.7042319Z     at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
2019-01-22T16:01:20.7042430Z    at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
2019-01-22T16:01:20.7042495Z    at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
2019-01-22T16:01:20.7042605Z    at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
2019-01-22T16:01:20.7042680Z    at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
2019-01-22T16:01:20.7042796Z    at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
2019-01-22T16:01:20.7042870Z    at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeDriverService service, ChromeOptions options, TimeSpan commandTimeout)
2019-01-22T16:01:20.7042984Z    at OpenQA.Selenium.Chrome.ChromeDriver..ctor(String chromeDriverDirectory, ChromeOptions options, TimeSpan commandTimeout)
2019-01-22T16:01:20.7043054Z    at OpenQA.Selenium.Chrome.ChromeDriver..ctor(String chromeDriverDirectory, ChromeOptions options)
2019-01-22T16:01:20.7043116Z    at OpenQA.Selenium.Chrome.ChromeDriver..ctor(String chromeDriverDirectory)
2019-01-22T16:01:20.7043224Z    at CS.Portal.E2e.Tests.E2ETestBase`1.SetupTest() in D:\a\1\s\CS.Portal.E2e.Tests\E2ETestBase.cs:line 48

**Comment by ShreyasRmsft** [comment]
@jfreal we released an update that should now automatically exit the test task once the tests complete regardless of whether there any stale driver processes etc. lingering on.

Even without the timeouts your test task should gracefully exit. Can you confirm if this is the case?

**Comment by jfreal** [comment]
@ShreyasRmsft, sorry, but I don't have enough bandwidth to turn off the timeout setting and re-run the test.

Today we re-ran the tests using Browser Stack Automate and 100% of the tests passed.  On Pipelines 10-20% of the tests are still failing.  Same code, same application, etc.

I'd love to help you figure out the issues but since this has been going on for over two months I'm afraid the company I work for is going to move on and use Browser Stack instead of waiting for the fix for whatever is wrong.

**Comment by jfreal** [comment]
5 runs in with Browser Stack, no changes, 100% pass rate.
