### ISSUE TITLE
Update/Add .Net Framework 4.7.2 and 4.8 to VS2017 and VS2019

### ISSUE THREAD

**Issue by sadjadbp** [microsoft/azure-pipelines-image-generation#888]
**Tool infomation**
- Tool name: .Net Framework
- Add or update? Update
- Desired version: 4.8
- If this is an add request:
  - Brief description of tool: 
  - URL for tool's homepage: 

**Areas and ecosystems**

- [ ] Android
- [ ] C / C++
- [ ] Container tools
- [ ] Database servers or clients
- [ ] General purpose tools
- [ ] Go
- [ ] Java
- [ ] Javascript, Node.js, and TypeScript
- [ ] iOS, macOS, and Apple-specific tools
- [x] .NET Core or .NET Desktop
- [ ] PHP
- [ ] Python
- [ ] Ruby
- [ ] Rust
- [ ] Scala
- [ ] Testing and code coverage
- [ ] Xamarin
- [ ] Other

**Image impacted**
Add the appropriate label for the image or images that should be updated (e.g., mac, ubuntu, window).
Windows

**Comment by jamshedd** [comment]
We need both .NET 4.7.2 and .NET 4.8 on the build agents so projects targeting either version can be built. While only 1 runtime can be installed at a time the targeting pack and .NET SDK are side by side, so both versions can and should be installed . The targeting pack and SDK are bundled in the "developer pack". 

Here are the 2 developer packs that need to be installed: 
.NET 4.7.2 dev pack: https://dotnet.microsoft.com/download/thank-you/net472-developer-pack
.NET 4.8 dev pack: https://dotnet.microsoft.com/download/thank-you/net48-developer-pack

**Comment by Suamere** [comment]
It is my understanding that changes to VM generation are pushed out every 3 weeks.  Right now I have .NET 4.8 code in Dev and Test locally, working through all of my pipelines other than Azure.

So, as an interested party, I'd like to know which 3-week period this will be pushed, so I can decide whether to revert a couple dozen NuGet packages to 4.7, or if I should wait.

**Comment by kaylangan** [comment]
@Suamere we have started the work on this feature and once it's complete, you can expect it to roll out in 3 or so weeks.

**Comment by kaylangan** [comment]
@sadjadbp @jamshedd @Suamere do you need .NET Framework 4.8 added to VS2017? Just VS2019?

**Comment by vdevappa** [comment]
To both.

**Comment by Suamere** [comment]
To be clear, this is the Azure Pipeline thread, correct?  As far as I know, generically speaking, .NET Framework 4.8 already works in Visual Studio 2017 and 2019.  The Azure Pipelines just need to have the SDK installed on the machines, and for the drop-down to be available and working through the Azure Portal.  

It shouldn't matter which Visual Studio I'm using to develop in, other than the versioning of the sln file and maybe something else.  But I don't know why it's complicated... Microsoft owns .NET and Azure, they said .NET 4.8 was fully released now, but .NET 4.8 only works locally, not in Azure.  So it needs to work in Azure... 

vdevappa and I don't represent the community as a whole, and shouldn't be required to specify which subsystems on the machine behind the scenes should be configured.  If I can do it locally with default Microsoft configurations, it should work by default through Azure.

**Comment by vdevappa** [comment]
Agreed! I think they are asking because the VS 2017 OS Image and the 2019 OS image are different. Should not matter though. It should go to any OS image with a VS version which can build a .NET 4.8 app.

**Comment by jamshedd** [comment]
@kaylangan, we need .the NET 4.8 dev pack installed for both VS 2017 and VS 2019. We also need the 4.7.2 dev pack installed for VS 2017 (since is only a part of VS 2019 and not VS 2017).

**Comment by virzak** [comment]
> @Suamere we have started the work on this feature and once it's complete, you can expect it to roll out in 3 or so weeks.

Hi, do you have an ETA for the rollout? I noticed that the relevant PR has been merged.

**Comment by kaylangan** [comment]
It should go out with the M152 release which we are tentatively planning to start next week. It may take time to reach your account though, depending on what ring your account is on.

**Comment by kaylangan** [comment]
Completed  in #928.

**Comment by mattcwebster** [comment]
> Completed in #928.

Do you know when thi swill be released for Azure Pipelines, I just had a build fail after upgrading to 4.8.  

[error]C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1179,5): Error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.8" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.

**Comment by kaylangan** [comment]
No date for M152 yet. You'll see us create branches like `releases/VS2017/152.x` when we start generating candidate images.

**Comment by jkonecki** [comment]
To be honest this situation is bordering on ridiculus.
Version 4.8 has been released over a month ago and we still don't even have a planned release date!
I don't suppose the team was surprised by an unexpected release of .Net Framework.

Please provide the planned release date - it's hard to believe you don't have any dates for the next release which is supposed to be happening every 3-4 weeks.

**Comment by kaylangan** [comment]
Thank you for your patience. The reason I was unable to give a date for the M152 release is because our M151 deployment was delayed by a few bugs. We're on track to complete the M151 deployment by the end of the week. The M152 deployment will start next week and will progressively roll out across multiple rings. If we find bugs as it rolls out, the deployment gets paused until they are fixed. That's why I can't give you an exact date. I hope you understand.

**Comment by jkonecki** [comment]
Hi @kaylangan. This is the kind of update I was hoping for - I fully appreciate you don't know the exact date. The above definitely helps with planning work. Many thanks

**Comment by virzak** [comment]
@kaylangan, I know you guys work hard on the releases, but I was wondering if there is an ETA for 4.8 at this time.

**Comment by kaylangan** [comment]
@virzak plan is to start deploying M153 next week. Because of the delay in getting M151 out the door, we'll be skipping forward to M153 next week (which will also have the M152 changes). Thanks for the patience. 😃

**Comment by c0shea** [comment]
@kaylangan Is this being rolled out this week or has it been delayed again?

**Comment by shareonline** [comment]
> @kaylangan Is this being rolled out this week or has it been delayed again?

I wanna know this to. The issue is closed, but my builds keep failing with error thet 4.8 is not present?
Using hosted VS2019 as agent..

**Comment by joebourneMS** [comment]
Hi Folks, the S153 deployment is currently in progress, we expect it to be rolled out everywhere  by Monday. @shadyysf FYI

**Comment by shareonline** [comment]
> Hi Folks, the S153 deployment is currently in progress, we expect it to be rolled out everywhere by Monday. @shadyysf FYI

Thanks for the update Joe. :)

**Comment by virzak** [comment]
The **Initialize job** task ouputs
`Current agent version: '2.153.1'`

However the error is still there:
```
##[error]C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(1183,5): Error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.8" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.
```

**Comment by shareonline** [comment]
> The **Initialize job** task ouputs
> `Current agent version: '2.153.1'`
> 
> However the error is still there:
> 
> ```
> ##[error]C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(1183,5): Error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.8" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.
> ```

OH no.. I really don't want to downgrade, and i have a scheduled release next week :(

**Comment by vdevappa** [comment]
I am just doing this manually until it is fixed. :-(

**Comment by yannduran** [comment]
@vdevappa how did you 'do it manually'?

**Comment by shareonline** [comment]
> @vdevappa how did you 'do it manually'?

I wanna know this to? :)

Still an error on agent: Current agent version: '2.153.2'

**Comment by vdevappa** [comment]
From Visual Studio. Also I have a script from the days before I implemented CI which can build and deploy as well.

**Comment by Jabol92** [comment]
Any update? If I understood correctly, support for .NET Framework 4.8 should be live yesterday

**Comment by shadyysf** [comment]
@Jabol92 unfortunately the deployment is currently delayed. We anticipate it will be out everywhere by Monday 06/24. I apologize for the inconvenience.

**Comment by xeonix** [comment]
.NET 4.8 was released on April 18th, 2019.
As of today, it's been 2 months since it was released but Azure DevOps Hosted Build Pipelines still don't support it. That’s annoying and embarrassing. Next time please do sync-ups with .NET team once they release something, cause otherwise it makes no sense to release it until it’s available to dev teams.
Didn’t know that I need to check CI/CD pipelines before upgrading .NET version, cause it may break everything.
Bad experience.

**Comment by shadyysf** [comment]
@xeonix, again I truly apologize for the delay on delivering this. The reason this was delayed for so long is that we've been working on improvements to how images used for builds and releases are built and deployed. This will certainly improve our cadence in the short future and allow us to deliver a great experience.

**Comment by c0shea** [comment]
@shadyysf The delay is becoming unacceptable. This was originally supposed to be in M152 but the release was canceled because it was so close to M153. Now M153 keeps getting delayed indefinitely. Is it also going to be canceled? I'm all for improving the image building and deployment process, but can't that be the focus after getting this release out the door. It's frustrating to keep our projects on hold since we don't know when .NET 4.8 will ever be supported in Azure DevOps.

**Comment by badluckjack** [comment]
@shadyysf Current agent version: 2.153.2 and still unable to build .NET 4.8.

I can't believe this issue status is closed when it is not yet resolved.  What a terrible policy.

**Comment by yannduran** [comment]
@shadyfcis I agree with @badluckjack

This issue should be **re-opened** until such time we can actually use .NET 4.8 in Azure DevOps Pipelines! @kaylangan should **not** have closed this until she had **verified** that real people were actually able to use it.

Too much of a rush to just get issued closed ASAP!!!

**Comment by thomasbrownflores** [comment]
I have been trying to work with this for the past month with responses of it will be out soon then you say it is out in 2.153.  Guess what it isn't.  This is holding up any release into my pipelines for 4.8.  Stop saying soon and just do it.,

**Comment by thomasbrownflores** [comment]
I have been trying to work with this for the past month with responses of it will be out soon then you say it is out in 2.153. Guess what it isn't. This is holding up any release into my pipelines for 4.8. Stop saying soon and just do it.,

**Comment by SoftwareDevExpert** [comment]
I have been trying to work with this for the past month with responses of it will be out soon then you say it is out in 2.153. Guess what it isn't. This is holding up any release into my pipelines for 4.8. Stop saying soon and just do it.,

**Comment by shadyysf** [comment]
I agree, the issue should not have been resolved until the fix rolls out. I will reopen. However, to clear the confusion the agent version is not the same as the image version. The agent version is the version of the build agent process that's dropped on the machine and not the version of the image used to create the machine. Those are 2 separate concepts. The M153 image version is still rolling out according to the schedule mentioned earlier.

**Comment by vdevappa** [comment]
> 
> 
> @shadyysf Current agent version: 2.153.2 and still unable to build .NET 4.8.
> 
> I can't believe this issue status is closed when it is not yet resolved. What a terrible policy.

That is what they do across the board. Seems like a MS company policy at this point. You guys won't believe I have a "paid" support ticket on this. And we are as helpless as you are!

**Comment by shareonline** [comment]
> I agree, the issue should not have been resolved until the fix rolls out. I will reopen. However, to clear the confusion the agent version is not the same as the image version. The agent version is the version of the build agent process that's dropped on the machine and not the version of the image used to create the machine. Those are 2 separate concepts. The M153 image version is still rolling out according to the schedule mentioned earlier.

Thx for clearing that up @shadyysf , it could help with peoples (me) "self-testing" and frustration..
I myself have downgraded to 4.7.2 until the fix is here. I understand that not all people can just do that, but works for me.
People including myself can be a little rough around the edges when management is pushing down on them i guess, but keep up the good work! Everybody can be delayed..

**Comment by virzak** [comment]
4.8 works! I can believable! Thank you!

**Comment by vdevappa** [comment]
> 
> 
> 4.8 works! I can believable! Thank you!

I still get the error. Are you using VS 2019 for the build?

C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\amd64\Microsoft.Common.CurrentVersion.targets(1179,5): Error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.8" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.
Process 'msbuild.exe' exited with code '1'.

**Comment by vdevappa** [comment]
For me, this works for my classic cloud service builds, but currently fails for the service fabric builds. Anybody can confirm the deployment status? Hello? Anybody there? Knock Knock...

**Comment by shadyysf** [comment]
@vdevappa , that update is out everywhere. Can you share your account name for investigation?

**Comment by vdevappa** [comment]
How do I send you a private message here?

**Comment by shadyysf** [comment]
@vdevappa feel free to send me the details of your issue as well as your Azure Devops account at shsamy@microsoft.com

**Comment by vdevappa** [comment]
FYI.. guys, this specific issue is resolved. I'm dealing with other artifacts maybe of the latest release now. :-(
